### ISSUE TITLE
Phone portrait mode photos are rotated by 90°

### ISSUE THREAD

**Issue by gregorni** [Talinx/jp2a#13] opened 2023-05-12 16:12 UTC
When converting images shot on a smartphone in portrait mode, the output is rotated anti-clockwise by 90°. This might have to do with the image metadata not being read properly, or at least not the part that tells that the image is rotated 90°.

**Comment by Talinx** [comment] 2023-05-12 16:26
Would you be able to share an image where this happens for debugging?
I was not able to reproduce this issue with my smartphone. Different software on different smartphones might rotate images using different techniques.

**Comment by gregorni** [comment] 2023-05-12 16:28
I found the issue on these two photos:

![2023-02-05-15-59-45-806](https://github.com/Talinx/jp2a/assets/119804311/97dcc3b2-ff00-427b-83b9-fba3cb5c45eb)

![IMG_20230512_180318](https://github.com/Talinx/jp2a/assets/119804311/eca11412-478a-4207-8f90-3bff49217237)

**Comment by gregorni** [comment] 2023-05-12 16:57
If it helps, [ascii-image-converter](https://github.com/TheZoraiz/ascii-image-converter) has the same problem.

**Comment by gregorni** [comment] 2023-06-28 07:35
I've talked about this with more people, and it seems to be a problem the image library used to open the image should take care of.

What library is jp2a using?

**Comment by Talinx** [comment] 2023-06-28 09:51
jp2a uses [libjpeg](https://ijg.org/). However most people will have the optimized version [libjpeg-turbo](https://libjpeg-turbo.org/) installed.

**Comment by gregorni** [comment] 2023-06-28 19:17
So the libjpeg-turbo devs rejected my issue. I guess someone will have to do a manual check for EXIF rotation tags, either jp2a or the frontend.

**Comment by Talinx** [comment] 2024-09-04 16:38
Added [support for Exif orientation](https://github.com/Talinx/jp2a/commit/6384d9669678d148cdfb747933858411787d85b3) using [libexif](https://libexif.github.io/), new release coming soon (or build from the [develop branch](https://github.com/Talinx/jp2a/tree/develop) right now).

**Comment by Talinx** [comment] 2024-09-22 17:13
Fixed in version [1.3.0](https://github.com/Talinx/jp2a/releases/tag/v1.3.0)

**Closed by Talinx** 2024-09-22 17:13 UTC
Labels: bug
